require('tjl/packer_init')
require('tjl/core/options')
require('tjl/core/keymaps')
require('tjl/core/colors')
require('tjl/plugins/nvim-tree')
require('tjl/plugins/indent-blankline')
require('tjl/plugins/feline')
